# Generated by Django 3.2.12 on 2022-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20210724_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
    ]
